### ISSUE TITLE
No such file or directory: '/dev/input/mouse0'

### ISSUE THREAD

**Issue by xavicolomer** [peterderivaz/pyopengles#2]
Hi there,

I was trying to run your code.:
python -i pyopengles.py

And I got this error:
numconfig= c_long(1)
Compiled
Compiled
Compiled

Traceback (most recent call last):
  File "pyopengles.py", line 413, in <module>
    m=pymouse.start_mouse()
  File "/home/pi/opengl/pyopengles/pymouse.py", line 43, in start_mouse
    m=MouseThread()
  File "/home/pi/opengl/pyopengles/pymouse.py", line 10, in **init**
    self.fd = open('/dev/input/mouse0','r')
IOError: [Errno 2] No such file or directory: '/dev/input/mouse0'

Any idea?

**Comment by xavicolomer** [comment]
Ok. I fixed because I was working remotelly with no mouse connected on the Raspberry Pi, so it wasn't creating the '/dev/input/mouse0'

But I have a new error now.

Traceback (most recent call last):
    File "pyopengles.py", line 410, in <module>
       egl = EGL()
    File "pyopengles.py", line 122, in **init**.py
       assert self.surface != EGL_NO_SURFACE
AssertionError

**Comment by peterderivaz** [comment]
I haven't seen that error myself.  A few things you could try:

1)
Check the resolution of the screen by adding 

```
  print width,height 
```

just before the assert to check that they have sensible values. (1280,720 or 1920,1080 might be expected)

2)
Check that you have enough memory assigned to the GPU
You used to be able to change the memory split by running

```
sudo cp /boot/arm128_start.elf /boot/start.elf
```

3)
Check that the default C OpenGL demos provided with the Raspberry Pi run.
e.g.  /opt/vc/src/hello_pi/hello_triangle/hello_triangle.bin
